version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - run: node --version
  test:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
      - run: node --version
  analyze:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run: npm audit
      - run: node --version

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test